### ISSUE TITLE
Atomを再起動すると設定画面が英語に戻ってしまう。

### ISSUE THREAD

**Issue by ksaito1125** [syon/atom-japanese-menu#9]
Atomにインストールした直後は、メニューも設定画面も日本語になります。
その後、Atomを終了し、起動するとメニューは日本語のままですが、設定画面が英語に戻ってしまいます。
<img width="1105" alt="2015-11-03 18 43 38" src="https://cloud.githubusercontent.com/assets/9954362/10905044/efc0465e-825a-11e5-80b1-e003fcf87dbb.png">

環境は、以下の通りです。
OS X 10.10.5
ATOM 1.1.0
japan-menu 1.5.0

**Comment by syon** [comment]
@ksaito1125 ご報告ありがとうございます。気づかなくてスミマセン。。
ショートカットキーではなく、メニューから選んで設定画面を開いた時に発生するようですね。
近々アップデートしますので、少々お待ちくださいませ。

**Comment by ksaito1125** [comment]
ありがとうございます。
ショートカットからだと問題ないのですね。

**Comment by syon** [comment]
修正版 v1.6.1 をリリースいたしました。
パッケージをアップデートしてご確認ください。
